import re
from typing import List, Dict, Any


# ============================================================
# CONFIGURATION
# ============================================================

# Approximate number of characters in each chunk.
#
# We use characters here instead of tokens because this
# processor does not need an LLM tokenizer.
#
# Later, when Ollama is connected, we can tune this according
# to the model's context window.
#
CHUNK_SIZE = 5000


# Number of characters that overlap between two chunks.
#
# Example:
#
# Chunk 1:
# A B C D E
#
# Chunk 2:
# D E F G H
#
# D and E provide context between chunks.
#
CHUNK_OVERLAP = 500


# ============================================================
# TEXT CLEANING
# ============================================================

def clean_text(text: str) -> str:
    """
    Clean extracted PDF text.

    PyMuPDF can sometimes return:
        multiple spaces
        excessive newlines
        strange whitespace

    We clean that here before chunking.
    """

    if not text:
        return ""

    # Replace Windows line endings
    text = text.replace(
        "\r\n",
        "\n"
    )

    # Replace multiple spaces/tabs
    text = re.sub(
        r"[ \t]+",
        " ",
        text
    )

    # Remove excessive blank lines
    text = re.sub(
        r"\n\s*\n+",
        "\n\n",
        text
    )

    return text.strip()


# ============================================================
# PAGE EXTRACTION
# ============================================================

def split_into_pages(
    text: str
) -> List[Dict[str, Any]]:
    """
    Convert the text generated by our PDF reader into
    individual pages.

    Our PDF reader stores pages like:

        ===== PAGE 1 =====
        page text

        ===== PAGE 2 =====
        page text
    """

    if not text:
        return []

    pattern = r"===== PAGE (\d+) ====="

    matches = list(
        re.finditer(
            pattern,
            text
        )
    )

    pages = []

    for index, match in enumerate(matches):

        page_number = int(
            match.group(1)
        )

        start = match.end()

        # Find where this page ends.
        if index + 1 < len(matches):

            end = matches[
                index + 1
            ].start()

        else:

            end = len(text)

        page_text = text[
            start:end
        ]

        page_text = clean_text(
            page_text
        )

        if page_text:

            pages.append({
                "page_number": page_number,
                "text": page_text
            })

    return pages


# ============================================================
# CHUNK TEXT
# ============================================================

def create_chunks(
    text: str,
    chunk_size: int = CHUNK_SIZE,
    overlap: int = CHUNK_OVERLAP
) -> List[str]:
    """
    Split text into overlapping chunks.

    We try to break at a natural boundary such as a sentence
    instead of blindly cutting in the middle of a sentence.
    """

    text = clean_text(
        text
    )

    if not text:
        return []

    if len(text) <= chunk_size:

        return [text]

    chunks = []

    start = 0

    while start < len(text):

        end = min(
            start + chunk_size,
            len(text)
        )

        chunk = text[
            start:end
        ]

        # ----------------------------------------------------
        # Try to end at a natural sentence boundary
        # ----------------------------------------------------

        if end < len(text):

            last_period = chunk.rfind(
                ". "
            )

            last_question = chunk.rfind(
                "? "
            )

            last_exclamation = chunk.rfind(
                "! "
            )

            boundary = max(
                last_period,
                last_question,
                last_exclamation
            )

            # Only use the boundary if it is reasonably
            # close to the end of the chunk.
            if boundary > chunk_size * 0.60:

                end = start + boundary + 1

                chunk = text[
                    start:end
                ]

        chunk = chunk.strip()

        if chunk:

            chunks.append(
                chunk
            )

        # ----------------------------------------------------
        # Move forward while keeping overlap
        # ----------------------------------------------------

        next_start = end - overlap

        # Safety protection against infinite loops.
        if next_start <= start:

            next_start = end

        start = next_start

    return chunks


# ============================================================
# PROCESS ONE PAPER
# ============================================================

def process_paper(
    paper: Dict[str, Any]
) -> List[Dict[str, Any]]:
    """
    Convert one paper's full extracted corpus into
    page-aware evidence chunks.
    """

    title = paper.get(
        "title",
        "Unknown Paper"
    )

    source = paper.get(
        "source",
        "unknown"
    )

    paper_url = paper.get(
        "paper_url"
    )

    pdf_url = paper.get(
        "pdf_url"
    )

    full_text = paper.get(
        "text",
        ""
    )

    pages = split_into_pages(
        full_text
    )

    evidence = []

    chunk_id = 0

    for page in pages:

        page_number = page[
            "page_number"
        ]

        page_text = page[
            "text"
        ]

        chunks = create_chunks(
            page_text
        )

        for chunk in chunks:

            chunk_id += 1

            evidence.append({

                # Unique identifier for this evidence
                "chunk_id": (
                    f"{source}_"
                    f"{chunk_id}"
                ),

                # Paper information
                "title": title,

                "source": source,

                "paper_url": paper_url,

                "pdf_url": pdf_url,

                # Exact page
                "page_number": page_number,

                # Actual evidence
                "text": chunk
            })

    return evidence


# ============================================================
# PROCESS COMPLETE CORPUS
# ============================================================

def process_corpus(
    corpus: List[Dict[str, Any]]
) -> List[Dict[str, Any]]:
    """
    Convert the entire PDF corpus into evidence chunks.
    """

    all_evidence = []

    for paper in corpus:

        paper_evidence = process_paper(
            paper
        )

        all_evidence.extend(
            paper_evidence
        )

    return all_evidence